### ISSUE TITLE
Project Crypto -  Play to win 

### ISSUE THREAD

**Issue by Pauloarjrpro** [angelobdev/north#1]
I specialize in mechanics and have extensive knowledge in game economics and blockchain technologies. I'm developing an open world game model that takes place in a city called Infinity City where each character will be part of an ecosystem that simulates reality. The game must be created based on the habbo hotel and adapted to the needs of development and adaptation. Wouldn't you like to be a part of it?

A global in-game economy running through blockchain can make the team's share of tokens super-valued by monetizing the game more quickly and consistently.

A great opportunity for those of us who are passionate about Habbo and know that this project has lost the technology race, aiming only at profit and without giving the due remuneration that players dreamed of and that they achieved with the parallel trade of items and modes.

**Comment by angelobdev** [comment]
Hi, sorry to answer you so late.... unfortunately I can't participate in your project at the moment. In any case, I wish you all the best!
